/******************************************************************************
 *
 * Module: SENSOR
 *
 * File Name: hcsr04_ultrasonic_sensor.c
 *
 * Description: Source file for the SENSOR driver
 *
 * Author: Nada Amged
 *
 *******************************************************************************/


#include "common_macros.h"
#include "hcsr04_ultrasonic_sensor.h"
#include "icu.h"
#include <util/delay.h>
/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint8 g_edges =0;
uint16 g_timerValue =0;

/*******************************************************************************
 *                          Functions Definitions                              *
 *******************************************************************************/

/*
 * Description
 * 1.Initialize the ICU driver as required.
 * 2.Setup the ICU call back function.
 * 3.Setup the direction for the trigger pin as output pin through the
 *   GPIO driver.
 */


void Ultrasonic_init(void){
	Icu_ConfigType Config_Ptr = {F_CPU_8 ,RISING};
	Icu_init(&Config_Ptr);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(TRIGGER_PULSE_DURATION);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);

}

/*
 * Description:
 *  1.Send the trigger pulse by using Ultrasonic_Trigger function.
 *  2.Start the measurements by the ICU from this moment.
 * Output:
 *  The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void){
	uint16 distance;
	Ultrasonic_Trigger();

	/*
	 * distance is calculated by knowing the "The time for which the echo pin remains high" and the velocity of Sound
	 *
	 * V=34000 cm/s
	 * total distance = 34000 * Time
	 *
	 * distance from object = (34000 * Time) / 2    "Divided by 2 because the time taken to object and back"
	 *
	 * */

	distance = (uint16)(g_timerValue/58.8);

	return (distance+2);
}


/*
 * Description:
 *  1.This is the call back function called by the ICU driver.
 *  2.This is used to calculate the high time (pulse time) generated by the Ultrasonic sensor.
 *
 */
void Ultrasonic_edgeProcessing(void){
	g_edges++;

	if(g_edges == 1){

		Icu_clearTimerValue();

		/*detect the falling edge*/
		Icu_setEdgeDetectionType(FALLING);

	}
	else if(g_edges == 2){

		/*get the Timer1 Value when the input is captured*/
		g_timerValue = Icu_getInputCaptureValue();

		/*clear the timer  to start from zero*/
		Icu_clearTimerValue();

		/*detect the rising edge*/
		Icu_setEdgeDetectionType(RISING);

		/*reset the counter of the edges for the next time */
		g_edges =0;
	}

}
