 /******************************************************************************
 *
 * Module: SENSOR
 *
 * File Name: hcsr04_ultrasonic_sensor.h
 *
 * Description: Header file for the SENSOR driver
 *
 * Author: Nada Amged
 *
 *******************************************************************************/

#ifndef HCSR04_ULTRASONIC_SENSOR_H_
#define HCSR04_ULTRASONIC_SENSOR_H_

#include "gpio.h"
#include "std_types.h"

#define ULTRASONIC_TRIGGER_PORT_ID      PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID       PIN5_ID
#define TRIGGER_PULSE_DURATION          10

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description
 * 1.Initialize the ICU driver as required.
 * 2.Setup the ICU call back function.
 * 3.Setup the direction for the trigger pin as output pin through the
 *   GPIO driver.
*/
void Ultrasonic_init(void);

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 *  1.Send the trigger pulse by using Ultrasonic_Trigger function.
 *  2.Start the measurements by the ICU from this moment.
 * Output:
 *  The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void);


/*
 * Description:
 *  1.This is the call back function called by the ICU driver.
 *  2.This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *
 */
void Ultrasonic_edgeProcessing(void);

#endif /* HCSR04_ULTRASONIC_SENSOR_H_ */
